apiVersion: v1
kind: Service
metadata:
  name: bazarr # radarr for example 
  namespace: media
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 6767
  selector:
    app: bazarr # radarr for example