apiVersion: v1
kind: Service
metadata:
  name: filebrowser # radarr for example 
  namespace: filebrowser
spec:
  type: ClusterIP
  ports:
    - port: 
      targetPort: 
  selector:
    app: filebrowser # radarr for example