apiVersion: v1
kind: Service
metadata:
  name: glance # radarr for example 
  namespace: glance
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: glance # radarr for example