apiVersion: v1
kind: Service
metadata:
  name: immich # radarr for example 
  namespace: immich
spec:
  type: ClusterIP
  ports:
    - port: 
      targetPort: 
  selector:
    app: immich # radarr for example