apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseer
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseer
  template:
    metadata:
      labels:
        app: jellyseer
    spec:
      nodeSelector:
        role: media
      containers:
      - name: jellyseer
        image: fallenbagel/jellyseerr
        env:
        - name: PUID
          value: "1056" 
        - name: PGID
          value: "1057" 
        volumeMounts:
        - name: config
          mountPath: /app/config
        ports:
        - containerPort: 5055
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyseer