apiVersion: v1
kind: Pod
metadata:
  name: glance-test-pod
  namespace: glance
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: glance-storage
      mountPath: /mnt/glance
  volumes:
  - name: glance-storage
    persistentVolumeClaim:
      claimName: glance
  restartPolicy: Never