apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-storage
spec:
  capacity:
    storage: 3000Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data
    server: media-node
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3000Gi
  volumeName: media-storage
  storageClassName: ""
