apiVersion: v1
kind: Service
metadata:
  name: cleanuparr # radarr for example 
  namespace: media
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 11011
  selector:
    app: cleanuparr # radarr for example