apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-suite-cert
  namespace: media
spec:
  secretName: media-suite-tls
  issuerRef:
    name: letsencrypt-cloudflare   # Your ClusterIssuer name
    kind: ClusterIssuer
  dnsNames:
    - jellyfin.example.org
    - jellyseer.example.org
    - qbittorrent.example.org
    - prowlarr.example.org
    - radarr.example.org
    - sonarr.example.org
    - immich.example.org
    - homepage.example.org
    - cloud.example.org