apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-suite-cert
  namespace: media
spec:
  secretName: media-suite-tls
  issuerRef:
    name: letsencrypt-cloudflare   # Your ClusterIssuer name
    kind: ClusterIssuer
  dnsNames:
    - jellyfin.example.com
    - jellyseer.example.com
    - qbittorrent.example.com
    - prowlarr.example.com
    - radarr.example.com
    - sonarr.example.com