apiVersion: v1
kind: Service
metadata:
  name: jellyfin # radarr for example 
  namespace: media
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8096
  selector:
    app: jellyfin # radarr for example
