apiVersion: v1
kind: Service
metadata:
  name: jellyseer # radarr for example 
  namespace: media
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5055
  selector:
    app: jellyseer # radarr for example
