apiVersion: v1
kind: Service
metadata:
  name: prowlarr # radarr for example 
  namespace: media
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9696
  selector:
    app: prowlarr # radarr for example
