apiVersion: v1
kind: Service
metadata:
  name: radarr # radarr for example 
  namespace: media
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 7878
  selector:
    app: radarr # radarr for example
