apiVersion: v1
kind: Service
metadata:
  name: sonarr # radarr for example 
  namespace: media
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8989
  selector:
    app: sonarr # radarr for example
